import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:flutter_application_1/models/child_profile.dart';
import 'package:flutter_application_1/models/vaccination_record.dart';

/// Service that generates shareable exports (PDF) for records.
class ExportService {
  ExportService._();

  /// Builds a vaccination summary PDF for the given child.
  static Future<Uint8List> buildVaccinationPdf({
    required ChildProfile child,
    required List<Vaccination> vaccinations,
    required List<VaccinationRecord> records,
  }) async {
    try {
      final doc = pw.Document();
      final df = DateFormat('yMMMd');

      final recordByVaccinationId = <String, VaccinationRecord>{
        for (final r in records) r.vaccinationId: r,
      };

      final completedCount = vaccinations
          .where((v) => recordByVaccinationId.containsKey(v.id))
          .length;

      doc.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(24),
          build: (context) => [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Vaccination Summary',
                      style: pw.TextStyle(
                        fontSize: 20,
                        fontWeight: pw.FontWeight.bold,
                      )),
                  pw.Text(df.format(DateTime.now())),
                ],
              ),
            ),
            pw.SizedBox(height: 8),
            pw.Container(
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey200,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Child: ${child.name}',
                      style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                  pw.SizedBox(height: 4),
                  pw.Text('Date of Birth: ${df.format(child.birthDate)}'),
                  pw.SizedBox(height: 2),
                  pw.Text('Age: ${child.ageInMonths} months'),
                  pw.SizedBox(height: 8),
                  pw.Text('Completed: $completedCount of ${vaccinations.length}'),
                ],
              ),
            ),
            pw.SizedBox(height: 16),
            pw.Table.fromTextArray(
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.grey300),
              cellAlignment: pw.Alignment.centerLeft,
              columnWidths: {
                0: const pw.FlexColumnWidth(2.2),
                1: const pw.FlexColumnWidth(1.2),
                2: const pw.FlexColumnWidth(1.2),
                3: const pw.FlexColumnWidth(1.6),
                4: const pw.FlexColumnWidth(2.0),
              },
              headers: const [
                'Vaccine',
                'Recommended',
                'Status',
                'Date Given',
                'Notes',
              ],
              data: vaccinations.map((v) {
                final rec = recordByVaccinationId[v.id];
                final status = rec != null ? 'Completed' : 'Pending';
                final date = rec != null ? df.format(rec.dateGiven) : '';
                final notes = rec?.notes ?? '';
                return [
                  v.name,
                  '${v.ageInMonths} mo',
                  status,
                  date,
                  notes,
                ];
              }).toList(),
            ),
            pw.SizedBox(height: 16),
            pw.Text(
              'Generated by Nesting Guide',
              style: pw.TextStyle(color: PdfColors.grey600, fontSize: 10),
            ),
          ],
        ),
      );

      return doc.save();
    } catch (e) {
      debugPrint('Failed to build vaccination PDF: $e');
      rethrow;
    }
  }

  /// Generates and opens the platform share/save UI for the vaccination PDF.
  static Future<void> shareVaccinationPdf({
    required ChildProfile child,
    required List<Vaccination> vaccinations,
    required List<VaccinationRecord> records,
  }) async {
    try {
      final bytes = await buildVaccinationPdf(
        child: child,
        vaccinations: vaccinations,
        records: records,
      );
      final safeName = child.name.replaceAll(RegExp(r'[^A-Za-z0-9_\-]'), '_');
      final date = DateFormat('yyyyMMdd').format(DateTime.now());
      await Printing.sharePdf(
        bytes: bytes,
        filename: 'vaccinations_${safeName}_$date.pdf',
      );
    } catch (e) {
      debugPrint('Failed to share vaccination PDF: $e');
      rethrow;
    }
  }
}
